version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run: docker run -d -it -p 9090:9090 -e "showQueryString=true" -e "showBody=true" -e "formatJson=true" -e "allowTvmTransferTrc10=1" --name tron trontools/quickstart
    - run: docker build -t tronwallet-contracts .
    - run: docker run -it --network=container:tron tronwallet-contracts